### ISSUE TITLE
script for automatically updating the boundary data version

### ISSUE THREAD

**Issue by jannikmi** [jannikmi/timezonefinder#167]
steps:
* create new branch
* download timezones-with-oceans.geojson.zip from https://github.com/evansiroky/timezone-boundary-builder/releases/latest
* unpack
* move .json to scripts folder
* execute file_converter.py
* update the existing binaries
* run ``tox`` and assert that all tests are passing
* bump version number in pyproject.toml (minor version bump)
* create new entry in changelog
* commit files
* raise Pull Request
* automatically merge if pipeline is running through

**Comment by jannikmi** [comment]
note: the `parse_data.sh` script can be used as baseline

**Comment by hemkdev** [comment]
Hi @jannikmi! Following up from #273 — I'd like to take this one too. 👋

Looking at the steps, I'd propose splitting it into three PRs, ordered by risk:

**PR 1 — make `parse_data.sh` CI-ready.** Replace the interactive `read` prompts with flags, auto-generate the changelog entry (the TODO already in the script), and clean up the version bump step. Fully testable locally, no workflow changes yet.

**PR 2 — automated update PR.** New workflow (triggered by the check from #273 instead of opening an issue): create a branch, run `make data`, commit, run the tests and open a PR. You'd still review and merge manually, but the manual effort drops to approving a ready-made PR.

**PR 3 — full automation.** Tag + auto-merge on green pipeline, creating the release. Kept last because it's the risky part (see question 2 below).

Two questions before I start:

1. **Version bump:** the issue says minor, but `parse_data.sh` currently does `uv version --bump patch` — and recent data-only releases (8.2.3, 8.2.5) were patch bumps. Which one should the automation use?
2. **Tag/auto-merge auth:** tags pushed with the default `GITHUB_TOKEN` don't trigger other workflows, so the tag wouldn't start the release pipeline in `build.yml`. Full automation needs a PAT or a GitHub App installation on the repo — only you can set that up. Fine to defer that to PR 3 and decide then?

If the split sounds good, I'll start with PR 1.

**Comment by Deniwn22** [comment]
One thing worth trying: setting the timeout at the transport layer rather than the request level — avoids the race condition.

**Comment by jannikmi** [comment]
Thank you @hemkdev 

Questions:
1. a patch version bump is fine
2. i will look into it. thanks for bringing it up.


about PR1:
- you could also translate the script to python if you think this is more convenient.
- feel free to pick a more suitable name for the script
- please change the 0/1 choices with self-explainatory options, for example: --dataset=full/same-since-now --with-oceans --rm-tmp

about PR2:
- couldn't you simply extend the GHA workflow from #273?

about PR3:
- I wonder what alerts (notifications) can be triggered to make all maintainers aware of a new PR with failing CI/CD

**Comment by jannikmi** [comment]
Hey @hemkdev! 👋

I've set up the GitHub App for handling tag/release automation. Here's what you need to know for PR 3:

**To get a token in the workflow:**

```yaml
- name: Generate GitHub App token
  id: app-token
  uses: actions/create-github-app-token@v1
  with:
    app-id: ${{ secrets.DATA_UPDATER_APP_ID }}
    private-key: ${{ secrets.DATA_UPDATER_PRIVATE_KEY }}
    owner: ${{ github.repository_owner }}

- name: Push tag (example)
  env:
    GH_TOKEN: ${{ steps.app-token.outputs.token }}
  run: |
    git tag ${{ env.VERSION_TAG }}
    git push origin ${{ env.VERSION_TAG }}
```

The token from the app will automatically trigger downstream workflows (like the release pipeline in build.yml), unlike the default `GITHUB_TOKEN`.

Let me know if you have questions of if there are any blockers
